# Generated by Django 5.1.4 on 2025-01-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheMenu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='item_image',
            field=models.CharField(default='https://cdn-icons-png.flaticon.com/512/2276/2276941.png', max_length=500),
        ),
    ]
