# Generated by Django 4.2 on 2025-06-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='genre',
            field=models.CharField(default='action', max_length=255),
        ),
    ]
