# Generated by Django 4.2 on 2025-06-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_API', '0002_moviedata_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='poster',
            field=models.ImageField(default='pictures/movie_posters/poster.jpg', upload_to='pictures/movie_posters/'),
        ),
    ]
